[package]
name = "podgrabv2"
version = "0.1.0"
edition = "2021"


[features]
# default = ["sqlite"]
# Empty to keep compatibility, prefer to set USE_SYSLOG=true
enable_syslog = []
mysql = ["diesel/mysql", "diesel_migrations/mysql"]
postgresql = ["diesel/postgres", "diesel_migrations/postgres"]
sqlite = ["diesel/sqlite", "diesel_migrations/sqlite", "libsqlite3-sys/bundled", "diesel/returning_clauses_for_sqlite_3_35"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = {version="0.11.14", features = ["blocking", "json", "async-compression", "rustls"]}
actix = "0.13.0"
async-recursion = "1.0.2"
r2d2 = "0.8.10"
base64 = "0.21.0"
actix-web-httpauth = "0.8.0"
uuid = {version="1.3.0", features = ["v4", "serde"]}
libsqlite3-sys = {version = "0.25.2", features = ["bundled"]}
diesel_migrations = "2.0.0"
actix-files = "0.6.2"
actix-web = "4.3.0"
jsonwebtoken = {version="8.2.0"}
log = "0.4.17"
opml = "1.1.5"
rand = "0.8.5"
chrono = {version  = "0.4.23", default-features=false, features = ["serde"]}
actix-web-actors = "4.2.0"
actix-cors="0.6.4"
rss = "2.0.2"
regex = "1.7.1"
diesel = { version = "2.0.3", features = ["chrono", "r2d2"] }
diesel_logger = { version = "0.2.0", optional = true }
utoipa = { version = "3", features = ["actix_extras"] }
futures = "0.3.26"
utoipa-swagger-ui = {version = "3", features = ["actix-web"] }
dotenvy = "0.15"
clokwerk= "0.4.0"
tokio = {version = "1.24.2", features = ["full"]}
serde = "1.0.152"
serde_derive = "1.0.152"
sysinfo = {version = "0.28.2", features = ["serde"]}
fs_extra = "1.3.0"
serde_json = "1.0.93"
dotenv = "0.15.0"
sha1 = "0.10.5"
paste = "1.0.12"