[package]
name = "podfetch"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[build-dependencies]
built = {version="0.6.0", features=["git2", "chrono", "semver"]}

[dependencies]
awc =  {version="3.1.1", features = ["rustls"]}
rpassword = "7.2.0"
reqwest = {version="0.11.14", features = ["blocking", "json", "async-compression", "rustls"]}
actix = "0.13.0"
async-recursion = "1.0.2"
base64 = "0.21.0"
actix-web-httpauth = "0.8.0"
uuid = {version="1.3.1", features = ["v4", "serde"]}
libsqlite3-sys = {version = "0.26.0", features = ["bundled"]}
diesel_migrations = "2.0.0"
actix-files = "0.6.2"
actix-web = {version="4.3.0", features=["rustls"]}
jsonwebtoken = {version="8.2.0"}
log = "0.4.17"
futures-util = "0.3.28"
opml = "1.1.5"
rand = "0.8.5"
env_logger = "0.10.0"
chrono = {version  = "0.4.23", default-features=false, features = ["serde"]}
actix-web-actors = "4.2.0"
rss = "2.0.2"
frankenstein = "0.25.0"
regex = "1.8.1"
xml-builder = "0.5.2"
diesel = { version = "2.0.4", features = ["sqlite", "returning_clauses_for_sqlite_3_35", "chrono", "r2d2"] }
r2d2 = "0.8.10"
utoipa = { version = "3", features = ["actix_extras"] }
futures = "0.3.28"
utoipa-swagger-ui = {version = "3", features = ["actix-web"] }
clokwerk= "0.4.0"
tokio = {version = "1.24.2", features = ["full"]}
serde = "1.0.162"
serde_derive = "1.0.152"
sysinfo = {version = "0.29.0", features = ["serde"]}
fs_extra = "1.3.0"
serde_json = "1.0.93"
dotenv = "0.15.0"
sha1 = "0.10.5"
sha256 = "1.1.3"