#[target."armv7-unknown-linux-musleabihf"]
#image.name = "alpine:edge"
#image.toolchain = ["x86_64-unknown-linux-musl"]
#pre-build = ["apk add pkgconfig openssl-dev libc-dev git"]

[target."x86_64-unknown-linux-musl"]
image.name = "ahuszagh/aarch64-cross:aarch64-unknown-linux-musl"
image.toolchain = ["linux/arm64=aarch64-unknown-linux-musl","x86_64-unknown-linux-musl","x86_64-unknown-linux-musl",
    "armv7-unknown-linux-musleabi"]
pre-build = ["uname -a && apt-get update && apt-get --assume-yes install libssl-dev pkgconfig git"]

[target."aarch64-unknown-linux-musl"]
image.name = "ahuszagh/aarch64-cross:aarch64-unknown-linux-musl"
image.toolchain = ["linux/arm64=aarch64-unknown-linux-musl","x86_64-unknown-linux-musl","aarch64-unknown-linux-musl",
    "armv7-unknown-linux-musleabi"]
pre-build = ["uname -a && apt-get update && apt-get --assume-yes install libssl-dev pkgconfig git"]

[target."armv7-unknown-linux-musleabi"]
image.name = "ahuszagh/aarch64-cross:aarch64-unknown-linux-musl"
image.toolchain = ["linux/arm64=aarch64-unknown-linux-musl","x86_64-unknown-linux-musl","aarch64-unknown-linux-musl",
    "armv7-unknown-linux-musleabi"]
pre-build = ["apt-get update && apt-get --assume-yes install libssl-dev pkgconfig git"]