#[target."armv7-unknown-linux-musleabihf"]
#image.name = "alpine:edge"
#image.toolchain = ["x86_64-unknown-linux-musl"]
#pre-build = ["apk add pkgconfig openssl-dev libc-dev git"]

[target."x86_64-unknown-linux-musl"]
image.name = "alpine:latest"
image.toolchain = ["linux/arm64=aarch64-unknown-linux-musl","x86_64-unknown-linux-musl","armv7-unknown-linux-musleabi"]
pre-build = ["apk add --no-cache gcc ca-certificates pkgconfig openssl-dev libc-dev git"]

[target."aarch64-unknown-linux-musl"]
image.name = "alpine:latest"
image.toolchain = ["linux/arm64=aarch64-unknown-linux-musl","x86_64-unknown-linux-musl","aarch64-unknown-linux-musl",
    "armv7-unknown-linux-musleabi"]
pre-build = ["apk add --no-cache gcc ca-certificates pkgconfig openssl-dev libc-dev git"]

[target."armv7-unknown-linux-musleabi"]
image.name = "alpine:latest"
image.toolchain = ["x86_64-unknown-linux-musl", "aarch64-apple-darwin","armv7-unknown-linux-musleabi"]
pre-build = ["apk add --no-cache ca-certificates gcc pkgconfig openssl-dev libc-dev git"]
