#[target."armv7-unknown-linux-musleabihf"]
#image.name = "alpine:edge"
#image.toolchain = ["x86_64-unknown-linux-musl"]
#pre-build = ["apk add pkgconfig openssl-dev libc-dev git"]

[target."x86_64-unknown-linux-musl"]
image.name = "multiarch/alpine:x86_64-latest-stable"
image.toolchain = ["linux/arm64=aarch64-unknown-linux-musl","x86_64-unknown-linux-musl","armv7-unknown-linux-musleabi"]
pre-build = ["apk add --no-cache binutils-x86_64 gcc ca-certificates musl-dev pkgconfig openssl-dev libc-dev git"]
env.passthrough = ["TARGET_CC=gcc"]

[target."aarch64-unknown-linux-musl"]
image.name = "alpine:latest"
image.toolchain = ["linux/arm64=aarch64-unknown-linux-musl","x86_64-unknown-linux-musl","aarch64-unknown-linux-musl",
    "armv7-unknown-linux-musleabi"]
pre-build = ["apk add --no-cache gcc ca-certificates musl-dev pkgconfig openssl-dev libc-dev git"]
env.passthrough = ["RUSTFLAGS", "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_RUSTFLAGS","TARGET_CC=gcc"]

[target."armv7-unknown-linux-musleabi"]
image.name = "multiarch/alpine:armv7-latest-stable"
image.toolchain = ["x86_64-unknown-linux-musl", "aarch64-apple-darwin","armv7-unknown-linux-musleabi"]
pre-build = ["apk add --no-cache ca-certificates gcc musl-dev pkgconfig openssl-dev libc-dev git"]
env.passthrough = ["TARGET_CC=gcc"]
